import {
  ArrowLeft,
  ArrowRight,
  BarChart3,
  BookOpen,
  Brain,
  Building,
  Building2,
  Calendar,
  Check,
  ChevronDown,
  CircleCheck,
  Clock,
  Cloud,
  Code,
  CreditCard,
  FlaskConical,
  FolderOpen,
  GraduationCap,
  Layers,
  Lightbulb,
  Link2,
  Loader2,
  Mail,
  MapPin,
  Menu,
  Newspaper,
  Palette,
  PenLine,
  Phone,
  RefreshCw,
  Rocket,
  Scale,
  Search,
  Share2,
  Shield,
  ShoppingCart,
  Stethoscope,
  Store,
  Users,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  layers: Layers,
  cloud: Cloud,
  brain: Brain,
  palette: Palette,
  graduation_cap: GraduationCap,
  users: Users,
  shopping_cart: ShoppingCart,
  stethoscope: Stethoscope,
  rocket: Rocket,
  building: Building,
  building_2: Building2,
  newspaper: Newspaper,
  code: Code,
  search: Search,
  scale: Scale,
  check: Check,
  arrow_right: ArrowRight,
  arrow_left: ArrowLeft,
  circle_check: CircleCheck,
  clock: Clock,
  flask_conical: FlaskConical,
  book_open: BookOpen,
  mail: Mail,
  phone: Phone,
  map_pin: MapPin,
  calendar: Calendar,
  folder_open: FolderOpen,
  store: Store,
  lightbulb: Lightbulb,
  menu: Menu,
  x: X,
  chevron_down: ChevronDown,
  loader: Loader2,
  facebook: Share2,
  linkedin: Link2,
  twitter: X,
  instagram: Share2,
  zap: Zap,
  credit_card: CreditCard,
  shield: Shield,
  bar_chart: BarChart3,
  edit: PenLine,
  refresh: RefreshCw,
};

export function InievoIcon({
  name,
  size = 20,
  className = "",
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Icon = ICON_MAP[name] ?? Layers;
  return <Icon size={size} className={className} aria-hidden />;
}
